language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

before_install:
  - wget http://www.phing.info/get/phing-latest.phar
  - chmod +x phing.phar
  - phpenv rehash

script:
  - phing.phar phplint phpunit
